In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
M = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]])

In [3]:
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]])

In [4]:
type(M)

numpy.ndarray

In [5]:
M.dtype

dtype('int64')

In [6]:
M = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.int8)
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [8]:
# order of matrix
M.shape

(4, 3)

In [9]:
M.size

12

In [10]:
M.ndim

2

In [11]:
M[0]

array([5, 4, 3], dtype=int8)

In [12]:
M[1]

array([1, 7, 8], dtype=int8)

In [13]:
M[1][2]

8

In [14]:
M[1,2]

8

In [15]:
M[1,2] = 4

In [16]:
M

array([[5, 4, 3],
       [1, 7, 4],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [17]:
print(M)

[[5 4 3]
 [1 7 4]
 [0 2 3]
 [7 5 1]]


In [18]:
M.reshape(3,4)

array([[5, 4, 3, 1],
       [7, 4, 0, 2],
       [3, 7, 5, 1]], dtype=int8)

In [19]:
M.reshape(-1, 2)

array([[5, 4],
       [3, 1],
       [7, 4],
       [0, 2],
       [3, 7],
       [5, 1]], dtype=int8)

In [20]:
M.reshape(2,-1)

array([[5, 4, 3, 1, 7, 4],
       [0, 2, 3, 7, 5, 1]], dtype=int8)

In [21]:
M.reshape(-1)

array([5, 4, 3, 1, 7, 4, 0, 2, 3, 7, 5, 1], dtype=int8)

In [22]:
M.flatten()

array([5, 4, 3, 1, 7, 4, 0, 2, 3, 7, 5, 1], dtype=int8)

In [23]:
v1 = np.array([3,4,2,1,6,5,4,7,8])

In [24]:
v1.shape

(9,)

In [26]:
v1.reshape(3,3)

array([[3, 4, 2],
       [1, 6, 5],
       [4, 7, 8]])

In [27]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
M.astype(np.float16)

array([[5., 4., 3.],
       [1., 7., 4.],
       [0., 2., 3.],
       [7., 5., 1.]], dtype=float16)

In [29]:
M.astype(np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [30]:
M.astype(np.unicode_)

array([['5', '4', '3'],
       ['1', '7', '4'],
       ['0', '2', '3'],
       ['7', '5', '1']], dtype='<U4')

In [31]:
print(M)

[[5 4 3]
 [1 7 4]
 [0 2 3]
 [7 5 1]]


In [32]:
for row in M:
    print(row)

[5 4 3]
[1 7 4]
[0 2 3]
[7 5 1]


In [33]:
for row in M:
    for value in row:
        print(value)

5
4
3
1
7
4
0
2
3
7
5
1


In [36]:
for row in M:
    for value in row:
        print(value, end =' ')
    print()

5 4 3 
1 7 4 
0 2 3 
7 5 1 


In [37]:
M.min()

0

In [38]:
M.max()

7

In [39]:
M.mean()

3.5

In [40]:
M.std()

2.179449471770337

In [41]:
M.var()

4.75

In [42]:
np.median(M)

3.5

In [43]:
M.sum()

42

In [44]:
Z = np.zeros([3,3], dtype = np.int8)
Z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [45]:
O = np.ones([3,3], dtype = np.int8)
O

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [46]:
S = np.arange(25).reshape(5,5)

In [47]:
S

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
S[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [50]:
S[:3,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [51]:
S[1:3,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [53]:
M > 4

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [ True,  True, False]])

In [54]:
M[M > 4]

array([5, 7, 7, 5], dtype=int8)

In [58]:
M[ M % 2 == 1]

array([5, 3, 1, 7, 3, 7, 5, 1], dtype=int8)

In [62]:
M1 = np.array([[6,8,7],[4,1,3],[5,2,9]])

In [65]:
# input matrix
M1

array([[6, 8, 7],
       [4, 1, 3],
       [5, 2, 9]])

In [66]:
# output matrix
np.array([[0,0,7],[0,1,3],[5,0,9]])

array([[0, 0, 7],
       [0, 1, 3],
       [5, 0, 9]])

In [68]:
M.shape[0]

4

In [72]:
for i in range(M1.shape[0]):
    for j in range(M1.shape[1]):
        if M1[i,j] % 2 == 0:
            M1[i,j] = 0

In [73]:
M1

array([[0, 0, 7],
       [0, 1, 3],
       [5, 0, 9]])

#### Matrix Operations

##### Addition

In [76]:
M1 = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.int8)
M2 = np.array([[2,8,1],[0,2,5],[1,9,4],[6,2,6]], dtype = np.int8)

In [77]:
M1.shape, M2.shape

((4, 3), (4, 3))

In [78]:
M3 = M1 + M2

In [79]:
M3

array([[ 7, 12,  4],
       [ 1,  9, 13],
       [ 1, 11,  7],
       [13,  7,  7]], dtype=int8)

In [80]:
M1 + 10

array([[15, 14, 13],
       [11, 17, 18],
       [10, 12, 13],
       [17, 15, 11]], dtype=int8)

In [81]:
M1 + [2,3,1]

array([[ 7,  7,  4],
       [ 3, 10,  9],
       [ 2,  5,  4],
       [ 9,  8,  2]])

##### Subtraction

In [83]:
M1 - M2

array([[ 3, -4,  2],
       [ 1,  5,  3],
       [-1, -7, -1],
       [ 1,  3, -5]], dtype=int8)

In [85]:
M2 - M1

array([[-3,  4, -2],
       [-1, -5, -3],
       [ 1,  7,  1],
       [-1, -3,  5]], dtype=int8)

In [86]:
abs(M1 - M2)

array([[3, 4, 2],
       [1, 5, 3],
       [1, 7, 1],
       [1, 3, 5]], dtype=int8)

In [87]:
M1 = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.uint8)
M2 = np.array([[2,8,1],[0,2,5],[1,9,4],[6,2,6]], dtype = np.uint8)

In [88]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [89]:
M1 - M2

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

##### Scaler Multiplication

In [91]:
M

array([[5, 0, 3],
       [1, 7, 0],
       [0, 0, 3],
       [7, 5, 1]], dtype=int8)

In [92]:
3 * M

array([[15,  0,  9],
       [ 3, 21,  0],
       [ 0,  0,  9],
       [21, 15,  3]], dtype=int8)

In [95]:
3 * (M1 + M2)

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [96]:
3 * M1 + 3 * M2

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [97]:
(3 + 4) * M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [98]:
3 * M1 + 4 * M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [101]:
3 * 4 * M1, 4 * 3 * M1, M1 * ( 3 * 4)

(array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8))

In [102]:
-3 * M1

array([[-15, -12,  -9],
       [ -3, -21, -24],
       [  0,  -6,  -9],
       [-21, -15,  -3]], dtype=int16)

In [103]:
- (3 * M1)

array([[241, 244, 247],
       [253, 235, 232],
       [  0, 250, 247],
       [235, 241, 253]], dtype=uint8)

In [104]:
1 * M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [105]:
-1 * M1

array([[-5, -4, -3],
       [-1, -7, -8],
       [ 0, -2, -3],
       [-7, -5, -1]], dtype=int16)

##### Matrix Multiplication

In [111]:
M1 = np.array([[5,4,3],[1,7,8]], dtype = np.int8)
M2 = np.array([[2,8],[1,0],[2,5]], dtype = np.int8)

In [112]:
M1

array([[5, 4, 3],
       [1, 7, 8]], dtype=int8)

In [113]:
M2

array([[2, 8],
       [1, 0],
       [2, 5]], dtype=int8)

In [114]:
np.matmul(M1, M2)

array([[20, 55],
       [25, 48]], dtype=int8)

In [115]:
M1 @ M2

array([[20, 55],
       [25, 48]], dtype=int8)

In [116]:
M1 @ M2, M2 @ M1

(array([[20, 55],
        [25, 48]], dtype=int8),
 array([[18, 64, 70],
        [ 5,  4,  3],
        [15, 43, 46]], dtype=int8))

In [117]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[3, 8], [1, 6]])

In [122]:
A @ (B @ C),       (A @ B) @ C

(array([[ 79, 284],
        [179, 644]]),
 array([[ 79, 284],
        [179, 644]]))

In [123]:
A @ (B + C),      A @ B + A @ C

(array([[24, 42],
        [56, 98]]),
 array([[24, 42],
        [56, 98]]))

In [125]:
(A + B) @ C,     A @ C + B @ C

(array([[ 26,  96],
        [ 42, 152]]),
 array([[ 26,  96],
        [ 42, 152]]))

In [126]:
A * B

array([[ 5, 12],
       [21, 32]])

##### Matrix Transpose

In [129]:
M

array([[5, 0, 3],
       [1, 7, 0],
       [0, 0, 3],
       [7, 5, 1]], dtype=int8)

In [130]:
np.transpose(M)

array([[5, 1, 0, 7],
       [0, 7, 0, 5],
       [3, 0, 3, 1]], dtype=int8)

In [131]:
M.reshape(3, 4)

array([[5, 0, 3, 1],
       [7, 0, 0, 0],
       [3, 7, 5, 1]], dtype=int8)

In [132]:
M.T

array([[5, 1, 0, 7],
       [0, 7, 0, 5],
       [3, 0, 3, 1]], dtype=int8)

In [133]:
M, M.T.T

(array([[5, 0, 3],
        [1, 7, 0],
        [0, 0, 3],
        [7, 5, 1]], dtype=int8),
 array([[5, 0, 3],
        [1, 7, 0],
        [0, 0, 3],
        [7, 5, 1]], dtype=int8))

In [135]:
A.T + B.T,    (A + B).T

(array([[ 6, 10],
        [ 8, 12]]),
 array([[ 6, 10],
        [ 8, 12]]))

In [137]:
(3 * M).T,    3 * M.T

(array([[15,  3,  0, 21],
        [ 0, 21,  0, 15],
        [ 9,  0,  9,  3]], dtype=int8),
 array([[15,  3,  0, 21],
        [ 0, 21,  0, 15],
        [ 9,  0,  9,  3]], dtype=int8))

In [140]:
(A @ B).T,     B.T @ A.T

(array([[19, 43],
        [22, 50]]),
 array([[19, 43],
        [22, 50]]))

##### Read the size of matrix and then matrix values from user and print original matrix and its transpose

In [144]:
rows = int(input('How many rows? '))
cols = int(input('How many columns? '))
M0 = np.zeros([rows, cols], dtype=np.int16)

for i in range(rows):
    for j in range(cols):
        num = int(input('Enter value'))
        M0[i,j] = num

print("Original Matrix: \n", M0)
print("Transpose:\n", M0.T)

How many rows?  2
How many columns?  3
Enter value 5
Enter value 6
Enter value 4
Enter value 2
Enter value 9
Enter value 8


Original Matrix: 
 [[5 6 4]
 [2 9 8]]
Transpose:
 [[5 2]
 [6 9]
 [4 8]]


##### Trace

In [146]:
M1 = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.int8)
M2 = np.array([[2,8,1],[0,2,5],[1,9,4]], dtype = np.int8)

In [147]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [162]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [149]:
M1.shape

(4, 3)

In [150]:
M2.shape

(3, 3)

In [163]:
add = 0
for i in range(min(M1.shape)):
    add = M1[i,i] + add

In [164]:
add

15

In [165]:
add = 0
for i in range(min(M2.shape)):
    add = M2[i,i] + add
add

8

In [160]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [166]:
M1.diagonal()

array([5, 7, 3], dtype=int8)

In [167]:
M2.diagonal()

array([2, 2, 4], dtype=int8)

In [168]:
sum(M1.diagonal())

15

In [169]:
M2.diagonal().sum()

8

In [170]:
M1.trace()

15

In [171]:
np.trace(M2)

8

In [173]:
np.trace(A @ B),    np.trace(B @ A)

(69, 69)

In [178]:
M1.trace(),         M.T.trace()

(15, 15)

In [179]:
np.trace(M1 * 3),      3 * M1.trace()

(45, 45)

In [182]:
A.trace() + B.trace(),     np.trace(A + B)

(18, 18)

##### Determinant of matrix

In [186]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [187]:
np.linalg.det(M2)

-36.0

In [188]:
A

array([[1, 2],
       [3, 4]])

In [189]:
np.linalg.det(A)

-2.0000000000000004

##### Inverse of matrix

In [192]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [197]:
%precision 2
np.linalg.inv(M2)

array([[ 1.03,  0.64, -1.06],
       [-0.14, -0.19,  0.28],
       [ 0.06,  0.28, -0.11]])

In [194]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Rank of the matrix

In [199]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [201]:
np.linalg.matrix_rank(M1)

3

In [202]:
M3 = np.array([[1,2,3],[4,5,12],[2,7,6]])

In [203]:
M3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 2,  7,  6]])

In [205]:
M3[:,0]

array([1, 4, 2])

In [206]:
M3[:,0] * 3

array([ 3, 12,  6])

In [207]:
np.linalg.matrix_rank(M3)

2

In [209]:
M4 = np.array([[1,2,3],[4,8,12],[2,4,6]])

In [210]:
M4

array([[ 1,  2,  3],
       [ 4,  8, 12],
       [ 2,  4,  6]])

In [211]:
np.linalg.matrix_rank(M4)

1

#### Types of matrices

##### Row matrix

In [227]:
R = np.array([[3,4,5],[1,3,8]])

In [228]:
R

array([[3, 4, 5],
       [1, 3, 8]])

In [229]:
R = R.reshape(1,-1)

In [230]:
R

array([[3, 4, 5, 1, 3, 8]])

In [231]:
R.shape

(1, 6)

##### Column Matrix

In [221]:
C = np.array([[3,4,5],[1,3,8]])

In [222]:
C = C.reshape(-1, 1)

In [223]:
C

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [224]:
C.shape

(6, 1)

In [225]:
C.T

array([[3, 4, 5, 1, 3, 8]])

In [232]:
R.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

##### Square Matrix

In [234]:
S = np.array([[3,4,5],[1,3,8],[9,0,2]])

In [235]:
S

array([[3, 4, 5],
       [1, 3, 8],
       [9, 0, 2]])

In [236]:
def isSquareMatrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False

In [237]:
isSquareMatrix(S)

True

In [239]:
isSquareMatrix(M1)

False

##### Rectangular Matrix

In [240]:
def isRectangularMatrix(M):
    if M.shape[0] != M.shape[1]:
        return True
    else:
        return False

In [241]:
isRectangularMatrix(M1)

True

In [242]:
isRectangularMatrix(S)

False

##### Diagonal Matrix

In [245]:
np.random.randint(1,10)

7

In [247]:
# Create a diagonal square matrix with n rows/colums
# Read value of n from user and print the matrix

In [250]:
rc = int(input('Enter number of rows: '))
D = np.zeros([rc, rc], dtype=np.int16)
for i in range(rc):
    D[i,i] = np.random.randint(1,10)

D

Enter number of rows:  5


array([[9, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 3]], dtype=int16)

In [260]:
(D > 0).flatten().sum()

5

In [261]:
def isDiagonalMatrix(M):
    if (M > 0).flatten().sum() == M.shape[0]:
        return True
    else:
        return False

In [262]:
isDiagonalMatrix(D)

True

In [264]:
isDiagonalMatrix(M2)

False

##### Identity Matrix

In [266]:
I = np.zeros([4,4], dtype=np.int16)

In [270]:
rc = int(input('Enter number of rows: '))
I = np.zeros([rc, rc], dtype=np.int16)
for i in range(rc):
    I[i,i] = 1

I

Enter number of rows:  4


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [272]:
def isIdentityMatrix(M):
    if M.flatten().sum() == M.shape[0]:
        return True
    else:
        return False

In [273]:
isIdentityMatrix(I)

True

In [274]:
isIdentityMatrix(D)

False

##### Symmetric Matrix

In [277]:
S = np.array([[2,3,6],[3,4,5],[6,5,9]], dtype = np.int8)

In [278]:
S

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]], dtype=int8)

In [279]:
S.T

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]], dtype=int8)

In [281]:
(S == S.T).flatten().sum()

9

In [282]:
S.size

9

In [283]:
def isSymmetricMatrix(M):
    if (M == M.T).flatten().sum() == M.size:
        return True
    else:
        return False

In [284]:
isSymmetricMatrix(S)

True

In [286]:
isSymmetricMatrix(M2)

False

##### Skew-Symmetric Matrix

In [288]:
S1 = np.array([[0,3],[-3,0]])

In [289]:
S1

array([[ 0,  3],
       [-3,  0]])

In [290]:
-S1.T

array([[ 0,  3],
       [-3,  0]])

In [291]:
def isSkewSymmetricMatrix(M):
    if (M == -M.T).flatten().sum() == M.size:
        return True
    else:
        return False

In [292]:
isSkewSymmetricMatrix(S1)

True

In [293]:
isSkewSymmetricMatrix(S)

False

##### Orthogonal Matrix

In [294]:
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [295]:
I.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [299]:
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [309]:
Rm = np.array([[np.cos(50), -np.sin(50)],[np.sin(50), np.cos(50)]])

In [310]:
Rm

array([[ 1.,  0.],
       [-0.,  1.]])

In [311]:
Rm.T

array([[ 1., -0.],
       [ 0.,  1.]])

In [312]:
np.linalg.inv(Rm)

array([[ 1., -0.],
       [ 0.,  1.]])

In [317]:
# permutation matrix
P = np.array([[0,1,0],[1,0,0],[0,0,1]], dtype = np.int16)

In [318]:
P

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [319]:
P.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [320]:
np.linalg.inv(P)

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [321]:
np.linalg.det(P)

-1

In [322]:
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [328]:
M5 = np.array([[5,4,1,3],[8,9,0,3],[2,1,4,9],[7,3,1,4]])

In [329]:
M5

array([[5, 4, 1, 3],
       [8, 9, 0, 3],
       [2, 1, 4, 9],
       [7, 3, 1, 4]])

In [330]:
M5 @ I

array([[5, 4, 1, 3],
       [8, 9, 0, 3],
       [2, 1, 4, 9],
       [7, 3, 1, 4]])

##### Eigenvalues and Eigenvectors

In [333]:
A = np.array([[1,2],[3,4]], dtype = np.int8)

In [335]:
value, vector = np.linalg.eig(A)

In [336]:
value

array([-0.,  5.])

In [337]:
vector

array([[-1., -0.],
       [ 1., -1.]])

In [338]:
A @ vector

array([[ 0., -2.],
       [-0., -5.]])

In [340]:
value * vector

array([[ 0., -2.],
       [-0., -5.]])

In [341]:
A = np.array([[1,2,3,4],[3,4,5,6],[1,7,3,9],[8,7,3,5]], dtype = np.int8)

In [342]:
A

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 7, 3, 9],
       [8, 7, 3, 5]], dtype=int8)

In [343]:
value, vector = np.linalg.eig(A)

In [346]:
vector.dtype

dtype('complex128')