In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/home/mitu/Social_Network_Ads.csv')

In [3]:
df

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [4]:
# separate the features and labels
x = df[['Age','EstimatedSalary']]
y =df['Purchased']

In [5]:
# import the class
from sklearn.naive_bayes import GaussianNB

In [6]:
# create the object
nb = GaussianNB()

In [7]:
# apply the data / train the algorithm
nb.fit(x, y)

GaussianNB()

In [8]:
new = pd.DataFrame({
    'Age': [46,23,52],
    'EstimatedSalary': [67000,38700,140000]
})

In [9]:
new

Age  EstimatedSalary
0   46            67000
1   23            38700
2   52           140000

In [10]:
nb.predict_proba(new)

array([[0.48184269, 0.51815731],
       [0.98737899, 0.01262101],
       [0.00257448, 0.99742552]])

In [11]:
probs = nb.predict_proba(new)

In [14]:
probs.argmax(axis=1)

array([1, 0, 1])

In [15]:
new = pd.DataFrame({
    'Age': [46,23,52,21,40,33],
    'EstimatedSalary': [67000,38700,140000,50000,37000,20000]
})

In [16]:
nb.predict_proba(new)

array([[0.48184269, 0.51815731],
       [0.98737899, 0.01262101],
       [0.00257448, 0.99742552],
       [0.99114815, 0.00885185],
       [0.78537445, 0.21462555],
       [0.90556351, 0.09443649]])

In [17]:
nb.predict_proba(new).argmax(axis=1)

array([1, 0, 1, 0, 0, 0])